services:
  database:
    image: "postgres:16.10-alpine3.21"
    environment:
      POSTGRES_PASSWORD: 'local_password'
    ports:
     - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
