#!/bin/sh

MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

# Caso amend → não chama CZ
if [ -n "$SHA1" ]; then
  exit 0
fi

# Caso mensagem já exista → não chama CZ
if [ -s "$MSG_FILE" ]; then
  exit 0
fi

# Caso commit normal → abre menu CZ
exec < /dev/tty && npx cz --hook --no-editor
