#!/bin/sh
MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

REAL_MESSAGE=$(grep -v '^\s*#' "$MSG_FILE" | tr -d '[:space:]')

if [ -n "$SHA1" ]; then exit 0; fi
if [ -n "$REAL_MESSAGE" ]; then exit 0; fi

exec < /dev/tty && npx cz --hook "$MSG_FILE" --no-editor </dev/tty >/dev/tty 2>/dev/tty || true
